FROM chriswayg/tor-server
MAINTAINER David Parrish <daveparrish@tutanota.com>

RUN apt-get update && apt-get install -y --no-install-recommends tor-arm && \
  apt-get -y purge --auto-remove $build_deps && \
  apt-get clean && rm -r /var/lib/apt/lists/*

EXPOSE 9051
